AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Serverless Application

  Sample SAM Template for AWS Serverless Application

  '
Globals:
  Function:
    Environment:
      Variables:
        COURSE_TABLE: CourseTable
        USER_TABLE: UsersTable
    Timeout: 3
Resources:
  AddCourseFunction:
    Properties:
      CodeUri: s3://colib-digitial-hands-on-dynamo/d7f08b986cf5f5c8b487a4cd15fcafff
      Events:
        Createuser:
          Properties:
            Method: put
            Path: /users/{userid}/{courseid}
          Type: Api
      Handler: add_course.lambda_handler
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: UsersTable
      Runtime: python3.7
    Type: AWS::Serverless::Function
  CreateCourseFunction:
    Properties:
      CodeUri: s3://colib-digitial-hands-on-dynamo/d7f08b986cf5f5c8b487a4cd15fcafff
      Events:
        Createuser:
          Properties:
            Method: put
            Path: /courses/{courseid}
          Type: Api
      Handler: create_course.lambda_handler
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: UsersTable
      Runtime: python3.7
    Type: AWS::Serverless::Function
  CreateUserFunction:
    Properties:
      CodeUri: s3://colib-digitial-hands-on-dynamo/d7f08b986cf5f5c8b487a4cd15fcafff
      Events:
        Createuser:
          Properties:
            Method: put
            Path: /users
          Type: Api
      Handler: create_user.lambda_handler
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: UsersTable
      Runtime: python3.7
    Type: AWS::Serverless::Function
  GetCourseFunction:
    Properties:
      CodeUri: s3://colib-digitial-hands-on-dynamo/d7f08b986cf5f5c8b487a4cd15fcafff
      Events:
        Createuser:
          Properties:
            Method: get
            Path: /courses/{courseid}
          Type: Api
      Handler: get_course.lambda_handler
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: UsersTable
      Runtime: python3.7
    Type: AWS::Serverless::Function
  GetUserFunction:
    Properties:
      CodeUri: s3://colib-digitial-hands-on-dynamo/d7f08b986cf5f5c8b487a4cd15fcafff
      Events:
        Createuser:
          Properties:
            Method: get
            Path: /users/{userid}
          Type: Api
      Handler: get_user.lambda_handler
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: UsersTable
      Runtime: python3.7
    Type: AWS::Serverless::Function
  UsersTable:
    Properties:
      AttributeDefinitions:
      - AttributeName: user_id
        AttributeType: S
      - AttributeName: last_login
        AttributeType: N
      KeySchema:
      - AttributeName: user_id
        KeyType: HASH
      - AttributeName: last_login
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      TableName: UsersTable
    Type: AWS::DynamoDB::Table
Transform: AWS::Serverless-2016-10-31
