AWSTemplateFormatVersion: '2010-09-09'
	Transform: AWS::Serverless-2016-10-31
	Description: >
	    AWS Serverless Application

	    Sample SAM Template for AWS Serverless Application

	# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
	Globals:
	    Function:
	        Timeout: 3


	Resources:
	    CreateUserFunction:
	      Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
	      Properties:
	        CodeUri: .
	        Handler: create_user.lambda_handler
	        Runtime: python3.7
	        Events:
	          Createuser:
	            Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
	            Properties:
	              Path: /users/{userid}
	              Method: put
	    GetUserFunction:
	      Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
	      Properties:
	        CodeUri: .
	        Handler: get_user.lambda_handler
	        Runtime: python3.7
	        Events:
	          Createuser:
	            Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
	            Properties:
	              Path: /users/{userid}
	              Method: get
	    AddCourseFunction:
	      Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
	      Properties:
	        CodeUri: .
	        Handler: add_course.lambda_handler
	        Runtime: python3.7
	        Events:
	          Createuser:
	            Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
	            Properties:
	              Path: /users/{userid}/{courseid}
	              Method: put
	    CreateCourseFunction:
	      Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
	      Properties:
	        CodeUri: .
	        Handler: create_course.lambda_handler
	        Runtime: python3.7
	        Events:
	          Createuser:
	            Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
	            Properties:
	              Path: /courses/{courseid}
	              Method: put
	    GetCourseFunction:
	      Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
	      Properties:
	        CodeUri: .
	        Handler: get_course.lambda_handler
	        Runtime: python3.7
	        Events:
	          Createuser:
	            Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
	            Properties:
	              Path: /courses/{courseid}
	              Method: get